### ISSUE TITLE
K float regex vs Plutus spec float regex

### ISSUE THREAD

**Issue by ayberkt** [kframework/plutus-core-semantics#2]
In the [lexical grammar specification of Plutus Core](https://github.com/kframework/plutus-core-semantics/blob/master/docs/Plutus%20Core%20Lexical%20Grammar.pdf), the following regex is given for floats:
```
[+-]?[0-9]+(\.[0-9]+e?|e)
```
This differs from the regex for K's builtin `Float` sort. Since we most certainly do not want to re-implement float operations, we need to consider how we will hook this one to the built-in one.

This issue is not of extreme urgency as the K `Float` sort should be able to parse all Plutus floats. We should, however, still consider how we will handle this in the long term.

**Comment by daejunpark** [comment]
@ayberkt You may want to take a look at what KJS does:
https://github.com/kframework/javascript-semantics/blob/master/js-orig-syntax.k#L95-L96
while it uses the old K parser though.

**Comment by ayberkt** [comment]
Thanks @daejunpark! This was the kind of thing I was looking for.
