### ISSUE TITLE
Get everything working with the Scala backend

### ISSUE THREAD

**Issue by ayberkt** [kframework/plutus-core-semantics#21]
In the `scala-backend` branch, I changed the Makefile to
`kompile` with the Scala backend. Currently, all tests are failing.

We should get them passing soon.

Currently, running `./test_all.sh` results in the following
```
[Error] Internal: Uncaught exception thrown of type NullPointerException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
```

**Comment by nishantjr** [comment]
We've moved to K5 (ocaml backend)
