### ISSUE TITLE
how to run plc code?

### ISSUE THREAD

**Issue by clojurians-org** [kframework/plutus-core-semantics#39]
when i run the following code, it report ocaml error, 
where i can find the log? what's the right way to run it?
```shell
./build kplc run execution test/case-simple.plc
make: Nothing to be done for 'execution'.
make: Nothing to be done for 'translation'.
make: Nothing to be done for 'translate-to-iele'.
krun --directory /home/larluo/work/git/plutus-core-semantics/.build/execution test/case-simple.plc
Fatal error: exception Prelude.Stuck(_)
[Error] Critical: Failed to execute program in ocaml. See output for error
information.
```

**Comment by nishantjr** [comment]
Ah, again you've caught us relying on the test framework. I'd say the easiest way would be to write a test in `bin/test_plc.py`. The iele implementation requires that you pass in a JSON file including the iele program, the arguments and the expected output.

**Comment by clojurians-org** [comment]
i can't understand the JSON file format, 
can you offer me a format specification document link for iele-json?
thanks

**Comment by nishantjr** [comment]
https://github.com/runtimeverification/iele-semantics/blob/master/ethereum.md#running-tests

https://github.com/runtimeverification/iele-semantics/blob/master/ethereum.md#checking-state
